### ISSUE TITLE
json_dumps fails on Decimal

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.content#134]
```
(Pdb++) pprint(items)
[{u'CreationDate': '2017-06-22T18:13:06+02:00',
  u'Creator': 'admin',
  u'Description': '',
  u'EffectiveDate': 'None',
  u'ExpirationDate': 'None',
  u'Language': u'',
  u'ModificationDate': '2017-06-22T18:26:16+02:00',
  u'Subject': (),
  u'Title': 'Basis-Lizenz',
  u'Type': u'License Base',
  u'UID': u'86433e9fde3b4683a160a97d7150408f',
  u'exclude_from_nav': False,
  u'getIcon': Missing.Value,
  u'getMimeIcon': '/Plone/++resource++mimetype.icons/txt.png',
  u'getObjSize': '0 KB',
  u'getURL': 'http://localhost:11150/Plone/licenses/basis-lizenz',
  u'id': 'basis-lizenz',
  u'is_folderish': True,
  u'item_net': Decimal('149'),
  u'last_comment_date': None,
  u'mime_type': u'text/plain',
  u'path': '/licenses/basis-lizenz',
  u'portal_type': 'license',
  u'review_state': Missing.Value,
  u'total_comments': 0}]

(Pdb++) json_dumps({  'results': items[0],'total': total  })
*** ValueError: Circular reference detected

(Pdb++) items[0]['item_net']= 149
(Pdb++) json_dumps({  'results': items[0],'total': total  })
'{"total": 1, "results": {"getURL": "http://localhost:11150/Plone/licenses/basis-lizenz", "total_comments": 0, "Title": "Basis-Lizenz", "exclude_from_nav": false, "Type": "License Base", "id": "basis-lizenz", "last_comment_date": null, "UID": "86433e9fde3b4683a160a97d7150408f", "is_folderish": true, "ExpirationDate": "None", "ModificationDate": "2017-06-22T18:26:16+02:00", "review_state": null, "getMimeIcon": "/Plone/++resource++mimetype.icons/txt.png", "mime_type": "text/plain", "EffectiveDate": "None", "portal_type": "license", "Language": "", "path": "/licenses/basis-lizenz", "getObjSize": "0 KB", "Description": "", "Creator": "admin", "getIcon": null, "item_net": 149, "CreationDate": "2017-06-22T18:13:06+02:00", "Subject": []}}'

```

**Comment by jensens** [comment]
I think we should switch to simplejson which is in fact the ahead-developement version of whats in Python stdlib
```
~w/sandbox/simplejsontest$ ./bin/python
Python 2.7.13 (default, Jun 11 2017, 00:00:00) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> from decimal import Decimal
>>> json.dumps([Decimal(3)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Decimal('3') is not JSON serializable
>>> import simplejson
>>> simplejson.dumps([Decimal(3)])
'[3]'
```
